[project]
name = "local-chess"
version = "0.1.1"
description = "Chess, locally, in your terminal."
authors = [
    {name = "Leo Milligan",email = "leomilligan20@gmail.com"},
    {name = "Alainn Doyle",email = "alainndoyle@gmail.com"}
]
license = "GPL-3.0-only"
readme = "README.md"
keywords = [
  "chess",
  "chess-game",
  "chess-puzzle",
  "command-line",
  "game",
  "local-area-network",
  "local-chess",
  "local-first",
  "terminal",
  "textual",
  "tui"
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.14",
  "Environment :: Console",
  "Topic :: Games/Entertainment :: Board Games",
  "Intended Audience :: End Users/Desktop",
]
requires-python = ">=3.14,<4.0"
dependencies = [
    "textual (>=8.2.8,<9.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.scripts]
local-chess = "local_chess.entry_points:run"
