[project]
name = "local-chess"
version = "0.1.0"
description = "Chess, locally, in your Terminal."
authors = [
    {name = "Leo Milligan",email = "leomilligan20@gmail.com"},
    {name = "Alainn Doyle",email = "alainndoyle@gmail.com"}
]
license = "GNU General Public License v3.0"
requires-python = ">=3.14,<4.0"
dependencies = [
    "textual (>=8.2.8,<9.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
